package org.cheetahplatform.web.eyetracking.cleaning;

import org.cheetahplatform.web.dto.FilterRequest;
import org.cheetahplatform.web.dto.PupillometryFilterDto;

public interface IPupillometryFilter {

	PupillometryFilterDto getDto();

	long getId();

	String getName();

	/**
	 * Runs the filter.
	 *
	 * @param request
	 *            the filter request
	 * @param file
	 *            the pupillopmetry file
	 * @param fileId
	 *            the id of the currently processed file
	 * @return additional information generated by the filter to be displayed to the user.
	 * @throws Exception
	 *             if something goes wrong
	 */
	String run(FilterRequest request, PupillometryFile file, long fileId) throws Exception;
}
